version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=todo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root #todo hide password
    restart: unless-stopped
