server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: todo
      authentication-database: admin
      password: root
      username: root
      repositories:
        type: reactive
