name: Build and deploy JAR app to Azure Web App - Hbackend

on:
  push:
    paths-ignore:
      - "frontend"
    branches:
      - ci
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -f ./backend/pom.xml -Pprod

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: VismaHackathonBackend
          path: 'backend/target/*.jar'
          if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: VismaHackathonBackend

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Hbackend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E37A3ACCC48D4F4FB9C4EC170353F8B5 }}
          package: '*.jar'
